version: "3"

services:
  hayatdb:
    image: postgres:alpine
    container_name: hayatdb
    env_file: .env
    ports:
      - 5431:5432
    volumes:
      - ./shared:/dbdump
    networks:
      - mynet

networks:
  mynet: